# Case Study on Testing of Hypothesis

A company started to invest in digital marketing as a new way of their product
promotions.For that they collected data and decided to carry out a study on it.


In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [2]:
cd

C:\Users\windows


In [3]:
cd C:\Users\windows\Downloads

C:\Users\windows\Downloads


In [4]:
data = pd.read_csv('Sales_add.csv')

In [11]:
data

Month      Region      Manager  Sales_before_digital_add(in $)  \
0    Month-1  Region - A  Manager - A                          132921   
1    Month-2  Region - A  Manager - C                          149559   
2    Month-3  Region - B  Manager - A                          146278   
3    Month-4  Region - B  Manager - B                          152167   
4    Month-5  Region - C  Manager - B                          159525   
5    Month-6  Region - A  Manager - B                          137163   
6    Month-7  Region - C  Manager - C                          130625   
7    Month-8  Region - A  Manager - A                          131140   
8    Month-9  Region - B  Manager - C                          171259   
9   Month-10  Region - C  Manager - B                          141956   
10  Month-11  Region - B  Manager - C                          159339   
11  Month-12  Region - A  Manager - A                          178939   
12  Month-13  Region - B  Manager - A                          145062   
13  Month-14  Region - A  Manager - A                          151514   
14  Month-15  Region - C  Manager - A                          147463   
15  Month-16  Region - A  Manager - B                          177195   
16  Month-17  Region - A  Manager - C                          140862   
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
0                          270390  
1                          223334  
2                          244243  
3                          231808  
4                          258402  
5                          256948  
6                          222106  
7                          230637  
8                          226261  
9                          193735  
10                         203175  
11                         276279  
12                         205180  
13                         253131  
14                         229336  
15                         187305  
16                         234908  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

# ● The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.


In [12]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

let    	μ1 = average sales before digital marketing
    	
    μ2 = average sales after digital marketing

let the null hypothesis be:
    
    H0 = μ1 = μ2

the alternate hypothesis be:
  
    HA = 	μ1 < μ2

level of significance, α = 0.05

To test the hypothesis,

In [14]:
t_value, p_value = stats.ttest_ind(data['Sales_After_digital_add(in $)'], data['Sales_before_digital_add(in $)'], alternative='greater')

In [15]:
print("The t value is:", t_value)
print("The p value is: ", p_value)

The t value is: 12.995084451110877
The p value is:  1.3071840034523225e-16


This shows that the p value is smaller than level of significance, so we reject the null hypothesis.

Insights:
    
    we accept the alternative hypothesis, which means the average sales before digital marketing has increased after digital marketing. so there is an increase in sales after stepping into digital marketing.

# ● The company needs to check whether there is any dependency between the features “Region” and “Manager”.

we use chi square test

let null hypothesis,
H0 = The features Region and manager are independent

alternative hypothesis, HA = The features Region and manager are independent

level of significance, α = 0.05

In [9]:
contingencyTable = pd.crosstab(data['Manager'], data['Region'])
contingencyTable

Region       Region - A  Region - B  Region - C
Manager                                        
Manager - A           4           4           1
Manager - B           3           1           3
Manager - C           3           2           1

In [10]:
observedValues = contingencyTable.values
observedValues

array([[4, 4, 1],
       [3, 1, 3],
       [3, 2, 1]], dtype=int64)

In [11]:
x2, x2_p_value, deg_of_frdm, exp_val = stats.chi2_contingency(observed=observed_values)

In [12]:
print("The expected values are: \n\n", exp_val)
print("\nThe degree of freedom is: ", deg_of_frdm)

The expected values are: 

 [[4.09090909 2.86363636 2.04545455]
 [3.18181818 2.22727273 1.59090909]
 [2.72727273 1.90909091 1.36363636]]

The degree of freedom is:  4


In [13]:
print("The chi square statistic is : ", x2)
print("\nThe p-value for the chi square statistic is: ", x2_p_value)

The chi square statistic is :  3.050566893424036

The p-value for the chi square statistic is:  0.5493991051158094


Insights:
    
    p-value is higher than the level of significance. So we cannot reject the null hypothesis.
    Features are independent.